fragment File on File {
  __typename
  name
  url
  mime
  icon
  thumbnail
}

fragment FileInfo on File {
  __typename
  url
  name
  icon
  mime
  icon
  thumbnail
  metadata
  stats {
    creationTime
    lastWriteTime
    size
  }
}

query fileInfo($url: Url!) {
  file(url: $url) {
    ...FileInfo
  }
}

query listFiles($url: Url!) {
  directory(url: $url) {
    entries {
      ...File
    }
  }
}
