import fs from 'fs';
import path from 'path';
import { MetadataSchema } from '../metadata';
import messages from './messages.json';
import { MimetypeSchema } from '../mimetype';

function getMetadataMessageIds() {
  const messageIds = new Set();

  for (const metadataId of Object.keys(MetadataSchema)) {
    const parts = metadataId.split('.');
    parts.reduce((prev, part) => {
      const id = prev ? prev + '.' + part : part;
      messageIds.add('Metadata.' + id);
      return id;
    }, '');
    messageIds.add('Metadata.' + metadataId + '.Value');
  }

  return messageIds;
}

function generatePOFile() {
  const msgIds = [...messages, ...Array.from(getMetadataMessageIds()), ...MimetypeSchema.map((mimetype) => `MimeType:${mimetype.mime}`)];

  return `# This file is automatically generated by @anything/shared, please do not modify this file.
msgid ""
msgstr ""
"POT-Creation-Date: 2021-06-05 00:51+0800\\n"
"Mime-Version: 1.0\\n"
"Content-Type: text/plain; charset=utf-8\\n"
"Content-Transfer-Encoding: 8bit\\n"
"Language: \\n"

${msgIds.map((msgId) => `msgid "${msgId}"\nmsgstr ""`).join('\n\n')}
`;
}

fs.writeFileSync(path.join(__dirname, './generated/messages.pot'), generatePOFile());
