fragment File on File {
  _id
  __typename
  fileHandle {
    value
  }
  mime
  icon
  thumbnail
  stats {
    creationTime
    lastWriteTime
    size
  }
}

fragment FileInfo on File {
  _id
  __typename
  fileHandle {
    value
  }
  name
  mime
  icon
  thumbnail
  metadata
  tags
  stats {
    creationTime
    lastWriteTime
    size
  }
}

fragment Dirent on Dirent {
  name
  file {
    ...File
  }
}

query fileInfoByFileHandle($fileHandle: FileHandle!) {
  openFileHandle(fileHandle: $fileHandle) {
    openFile {
      ...FileInfo
    }
  }
}

query listFilesByUrl($url: Url!) {
  createFileHandle(url: $url) {
    openDirectory {
      entries {
        ...Dirent
      }
    }
  }
}

mutation addTags($fileHandle: FileHandle!, $tags: [String!]!) {
  addTags(fileHandle: $fileHandle, tags: $tags) {
    _id
    __typename
    tags
  }
}

mutation removeTags($fileHandle: FileHandle!, $tags: [String!]!) {
  removeTags(fileHandle: $fileHandle, tags: $tags) {
    _id
    __typename
    tags
  }
}