name: CI

on:
  - push

defaults:
  run:
    shell: bash

jobs:
  core:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - uses: actions/cache@v2
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
        restore-keys: |
          ${{ runner.os }}-nuget
    - name: Restore dependencies
      run: dotnet restore --locked-mode
    - name: Check style
      run: |
        dotnet tool update -g dotnet-format
        dotnet format --no-restore --fix-analyzers warn --fix-style warn --check
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-restore --no-build "/p:CollectCoverage=\"true\"" "/p:CoverletOutput=\"../../CoverageResults/\"" "/p:MergeWith=\"../../CoverageResults/coverage.json\"" "/p:CoverletOutputFormat=\"lcov,json\"" "/p:CopyLocalLockFileAssemblies=\"true\"" "-m:1"
    - uses: codecov/codecov-action@v1
      if: matrix.os == 'ubuntu-latest'
  web:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - name: Cache .pnpm-store
      uses: actions/cache@v2
      with:
        path:  ~/.pnpm-store
        key: ${{ runner.OS }}-node-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.OS }}-node-
          ${{ runner.OS }}-
    - name: Install pnpm
      run: npm install -g pnpm
    - name: Install dependencies
      run: pnpm install
    - name: Check
      run: pnpm run check
    - name: Build
      run: pnpm run build
